import os
import json
from summarize import convertnotes
from recommend import invokerecommendation
from langchain_openai import OpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
from langgraph.graph import StateGraph, START, END
from IPython.display import Image, display
from langchain.memory import ConversationBufferMemory
from findpatient import find_patient
import datetime
import dotenv



memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)

# Step 1: To create a LangGraph, we need to define the nodes and their connections

def patientdetails(node_input):
    print("****************************Welcome to the Aira MedAssist*****************************")
    DoctorName = input("Please enter the doctor's name: ")
    DoctorSpecialization = input("Please enter the doctor's specialization: ")
    print("***************************Please enter the patient details:***************************")
    HealthcardId = input("Please enter the health card ID: ").lower().strip()
    # Check if the patient already exists
    existing_patient = find_patient(HealthcardId)
    if existing_patient:
        print("Patient already exists. Here are the details:")
        print(json.dumps(existing_patient, indent=4))
        if input("Do you want to update the details? (yes/no): ").strip().lower() == 'yes':
            print("You can update the patient details below.")
            ClinicalNotes = input("Please enter the clinical notes: ")
            memory.chat_memory.add_user_message(f"{DoctorSpecialization} entered notes: {ClinicalNotes}")
            existing_patient["visit_history"].append({
                "visit_no": len(existing_patient["visit_history"]) + 1,  # Increment visit number
                "visitDate": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "DoctorName": DoctorName,
                "DoctorSpecialization": DoctorSpecialization,
                "ClinicalNotes": ClinicalNotes,
            })
            return existing_patient  # Return the updated patient details
        else:
            print("No updates made to the patient details.")
            return existing_patient
    else:
        print("No existing patient found with the provided health card ID.")
        PatientName = input("Please enter the name: ")
        PatientAge = int(input("Please enter the age: "))
        PatientGender = input("Please enter the gender: ")
        ClinicalNotes = input("Please enter the clinical notes: ")
        memory.chat_memory.add_user_message(f"{DoctorSpecialization} notes based on patient {PatientName}: {ClinicalNotes}")
        details_result = {
            "HealthcardId": HealthcardId,
            "Name": PatientName,
            "Age": PatientAge,
            "Gender": PatientGender,
            "visit_history": [{
                "visit_no": 1,  # Assuming this is the first visit
                "visitDate": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "DoctorName": DoctorName,
                "DoctorSpecialization": DoctorSpecialization,
                "ClinicalNotes": ClinicalNotes}]
            }

        return details_result  # Return the patient details as a dictionary


def summarize_notes(node_input):
    print("Processing the notes...")
    summary_text = convertnotes(node_input)
    print("Notes processed successfully!")

    summary_text= {
        "Subjective": summary_text.split("Objective:")[0].replace("Subjective:", "").strip(),
        "Objective": summary_text.split("Objective:")[1].split("Assessment:")[0].strip(),
        "Assessment": summary_text.split("Assessment:")[1].split("Plan:")[0].strip(),
        "Plan": summary_text.split("Plan:")[1].strip()
    }
    memory.chat_memory.add_ai_message(f"SOAP format generated by AIRA Medassist for {node_input['visit_history'][-1]['DoctorSpecialization']} entered Notes : {summary_text}")
    node_input["visit_history"][-1].update({"summary": summary_text})

    # If transcription already exists, append. If not, initialize.
    if "transcription" not in node_input:
        node_input["transcription"] = []

    # Append new messages from memory to global transcript
    node_input["transcription"].extend([m.content for m in memory.chat_memory.messages])


    print("node_input after summarization:", node_input)
    summary_result = node_input
    return summary_result  # Return the updated node input with the summary


def generate_referral_recommendation(node_input):
    print("Generating referral recommendation...")
    recommend_text = invokerecommendation(node_input)
    print("Referral recommendation generated successfully!")
    memory.chat_memory.add_ai_message(f"Aira Med Assist recommendation for {node_input['visit_history'][-1]['DoctorSpecialization']}: {recommend_text['recommendation']}")
    # memory.chat_memory.add_ai_message(f"Aira Med Assist decision for {node_input['visit_history'][-1]['DoctorSpecialization']}: {recommend_text['decision']}")
    memory.chat_memory.add_user_message(f"recommendation_status: {recommend_text['recommended']}")
    return node_input  # Return the updated node input with the recommendation and decision


def load_data(node_input):
    print("Loading data to file...")
    patient_info = node_input

    patient_info["transcription"].extend([msg.content for msg in memory.chat_memory.messages])

    filename = patient_info["HealthcardId"].replace(" ", "_").lower().strip()  # Create a filename from the patient's name
    os.makedirs("patient_db", exist_ok=True)
    with open(f"patient_db/{filename}.json", "w") as f:
        json.dump(patient_info, f, indent=4)
    print(f"Data saved to patient_db/{filename}.json")
    print("Data loaded successfully!")
    print("Thank you for using Aira MedAssist")



def main():

    graph = StateGraph(dict)
    graph.add_node( "Collect Patient Details",patientdetails)
    graph.add_node( "Summarize Clinical Notes",summarize_notes)
    graph.add_node("Generate Referral Recommendation",generate_referral_recommendation) 
    graph.add_node( "Load Data to File",load_data)

    graph.add_edge(START, "Collect Patient Details")
    graph.add_edge("Collect Patient Details", "Summarize Clinical Notes")   
    graph.add_edge("Summarize Clinical Notes", "Generate Referral Recommendation")
    graph.add_edge("Generate Referral Recommendation", "Load Data to File") 
    graph.add_edge("Load Data to File", END)
    # Run the graph
    result = graph.compile()
    result.invoke({})  # Execute the graph

    # Display the graph as an image
    print("................................Generating graph image........................................................")
    mermaid_code = result.get_graph().draw_mermaid()
    with open("graph.mmd", "w") as f:
        f.write(mermaid_code)
    print("Mermaid diagram saved to graph.mmd")




if __name__ == "__main__":
    main()
 